package io.syndesis.connector.springboot;

import javax.annotation.Generated;
import javax.sql.DataSource;

/**
 * SQL Stored Procedure Connector to invoke a SQL Stored Procedure
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.connector.SpringBootAutoConfigurationMojo")
public class SqlStoredConnectorConnectorConfigurationCommon {

    /**
     * Sets the DataSource to use to communicate with the database.
     */
    private DataSource dataSource;
    /**
     * Sets the StoredProcedure template to perform
     */
    private String template;
    /**
     * Enables or disables batch mode
     */
    private boolean batch = false;
    /**
     * If set will ignore the results of the template and use the existing IN
     * message as the OUT message for the continuation of processing
     */
    private boolean noop = false;
    /**
     * DB User Name
     */
    private String user;
    /**
     * DB User Password
     */
    private String password;
    /**
     * DB URL
     */
    private String url;
    /**
     * DB Schema
     */
    private String schema;
    /**
     * DB Catalog
     */
    private String catalog;

    public DataSource getDataSource() {
        return dataSource;
    }

    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public boolean isBatch() {
        return batch;
    }

    public void setBatch(boolean batch) {
        this.batch = batch;
    }

    public boolean isNoop() {
        return noop;
    }

    public void setNoop(boolean noop) {
        this.noop = noop;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getSchema() {
        return schema;
    }

    public void setSchema(String schema) {
        this.schema = schema;
    }

    public String getCatalog() {
        return catalog;
    }

    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }
}