package io.syndesis.connector.springboot;

import javax.annotation.Generated;
import javax.sql.DataSource;

/**
 * SQL Connector perform CRUD operations on a database
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.connector.SpringBootAutoConfigurationMojo")
public class SqlConnectorConnectorConfigurationCommon {

    /**
     * Sets the DataSource to use to communicate with the database.
     */
    private DataSource dataSource;
    /**
     * If set will ignore the results of the SQL query and use the existing IN
     * message as the OUT message for the continuation of processing
     */
    private boolean noop = false;
    /**
     * JDBC URL of the database
     */
    private String url = "jdbc:postgresql:database";
    /**
     * Username for the database connection
     */
    private String user;
    /**
     * Password for the database connection
     */
    private String password;
    /**
     * Database schema
     */
    private String schema;
    /**
     * Database catalog
     */
    private String catalog;

    public DataSource getDataSource() {
        return dataSource;
    }

    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public boolean isNoop() {
        return noop;
    }

    public void setNoop(boolean noop) {
        this.noop = noop;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSchema() {
        return schema;
    }

    public void setSchema(String schema) {
        this.schema = schema;
    }

    public String getCatalog() {
        return catalog;
    }

    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }
}